# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "galleries", :force => true do |t|
    t.column "user_id",      :integer,                    :null => false
    t.column "gallery_name", :string,   :default => "",   :null => false
    t.column "context",      :string
    t.column "password",     :string
    t.column "active",       :boolean,  :default => true, :null => false
    t.column "created_at",   :datetime,                   :null => false
    t.column "updated_at",   :datetime
  end

  add_index "galleries", ["gallery_name"], :name => "index_galleries_on_gallery_name", :unique => true
  add_index "galleries", ["context"], :name => "index_galleries_on_context", :unique => true
  add_index "galleries", ["user_id"], :name => "index_galleries_on_user_id"

  create_table "newsletter_subscribers", :force => true do |t|
    t.column "email", :string, :default => "", :null => false
  end

  add_index "newsletter_subscribers", ["email"], :name => "index_newsletter_subscribers_on_email", :unique => true

  create_table "photo_categories", :force => true do |t|
    t.column "category",   :integer,                    :null => false
    t.column "name",       :string,   :default => "",   :null => false
    t.column "active",     :boolean,  :default => true, :null => false
    t.column "created_at", :datetime,                   :null => false
    t.column "updated_at", :datetime
  end

  add_index "photo_categories", ["name"], :name => "index_photo_categories_on_name", :unique => true
  add_index "photo_categories", ["category"], :name => "index_photo_categories_on_category"

  create_table "photos", :force => true do |t|
    t.column "number",            :integer,                     :null => false
    t.column "orig_file_name",    :string,   :default => "",    :null => false
    t.column "shoot_id",          :integer,                     :null => false
    t.column "photo",             :binary,   :default => "",    :null => false
    t.column "show_on_home",      :boolean,  :default => false, :null => false
    t.column "photo_category_id", :integer
    t.column "active",            :boolean,  :default => true,  :null => false
    t.column "created_at",        :datetime,                    :null => false
    t.column "updated_at",        :datetime
  end

  add_index "photos", ["shoot_id", "number"], :name => "index_photos_on_shoot_id_and_number", :unique => true
  add_index "photos", ["photo_category_id"], :name => "index_photos_on_photo_category_id"
  add_index "photos", ["show_on_home"], :name => "index_photos_on_show_on_home"

  create_table "roles", :force => true do |t|
    t.column "name",       :string,   :default => "", :null => false
    t.column "created_at", :datetime,                 :null => false
    t.column "updated_at", :datetime
  end

  add_index "roles", ["name"], :name => "index_roles_on_name", :unique => true

  create_table "shoots", :force => true do |t|
    t.column "gallery_id", :integer,                    :null => false
    t.column "shoot_name", :string,   :default => "",   :null => false
    t.column "active",     :boolean,  :default => true, :null => false
    t.column "created_at", :datetime,                   :null => false
    t.column "updated_at", :datetime
  end

  add_index "shoots", ["gallery_id", "shoot_name"], :name => "index_shoots_on_gallery_id_and_shoot_name", :unique => true

  create_table "users", :force => true do |t|
    t.column "username",   :string,   :limit => 50, :default => "",   :null => false
    t.column "password",   :string,   :limit => 50
    t.column "role_id",    :integer,                                  :null => false
    t.column "active",     :boolean,                :default => true, :null => false
    t.column "created_at", :datetime,                                 :null => false
    t.column "updated_at", :datetime
  end

  add_index "users", ["username"], :name => "index_users_on_username", :unique => true
  add_index "users", ["role_id"], :name => "index_users_on_role_id"

end
